apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  labels:
    app: postgres-primary
spec:
  type: LoadBalancer  # RDSからアクセスできるようにLoadBalancerを使用
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres-primary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-primary-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-primary
  labels:
    app: postgres-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-primary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-primary
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
        - name: POSTGRES_DB
          value: postgres
        volumeMounts:
        - name: postgres-primary-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/custom-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-primary-storage
        persistentVolumeClaim:
          claimName: postgres-primary-pvc
      - name: postgres-config
        configMap:
          name: postgres-primary-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-primary-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    wal_level = logical
    max_wal_senders = 10
    max_replication_slots = 10
    max_logical_replication_workers = 10
    max_worker_processes = 20
    wal_sender_timeout = 0
    max_connections = 100
    shared_preload_libraries = 'pglogical'
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               md5
    host    replication     all             0.0.0.0/0               md5
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  user: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXM=  # postgres